[package]
name = "grant-duchars-dev"
version = "0.1.0"
authors = ["Grant Duchars"]
edition = "2021"
homepage = "grant.duchars.dev"

[dependencies]
leptos = { version = "0.7.8", features = ["csr"] }
console_error_panic_hook = "0.1.7"
leptos-use = "0.15.7"