name: Build and Deploy Website
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Target Wasm
      run: rustup target add wasm32-unknown-unknown --toolchain nightly
    - name: Get Trunk
      run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.14/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Build
      run: ./trunk build --release
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: dist
          single-commit: true
